services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: pnpm run dev --turbo
